In [1]:
import numpy as np

In [6]:
arr = np.arange(0,11)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr.max()

10

In [10]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
arr1 = np.array(my_list)

In [13]:
arr1   #2d Array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr1.max()

9

In [19]:
np.zeros((2,3)) #np.zeros(shape, dtype=float,etc)

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [20]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [21]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [22]:
np.linspace(0,10,20) #Linear distribution from 1 to 10 with 20 elements

array([  0.        ,   0.52631579,   1.05263158,   1.57894737,
         2.10526316,   2.63157895,   3.15789474,   3.68421053,
         4.21052632,   4.73684211,   5.26315789,   5.78947368,
         6.31578947,   6.84210526,   7.36842105,   7.89473684,
         8.42105263,   8.94736842,   9.47368421,  10.        ])

In [23]:
np.random.rand(5)

array([ 0.55335087,  0.09998609,  0.99856413,  0.34575156,  0.5818368 ])

In [25]:
arr2 = np.random.rand(5,5)

In [29]:
arr2.max(axis=1)

array([ 0.90799251,  0.87505514,  0.94762464,  0.95209653,  0.63126644])

In [27]:
arr2

array([[ 0.31219102,  0.90799251,  0.35147264,  0.40097717,  0.03041458],
       [ 0.08055783,  0.53198121,  0.33884948,  0.08573127,  0.87505514],
       [ 0.13654359,  0.77630592,  0.94762464,  0.50463209,  0.69245851],
       [ 0.04753157,  0.95209653,  0.69615515,  0.43974465,  0.34790385],
       [ 0.48928188,  0.2506753 ,  0.17795126,  0.63126644,  0.60396472]])

In [30]:
normal = np.random.randn(4,4) #return normal distribution of a function

In [31]:
normal  

array([[-1.91380085,  0.37796488,  0.0695682 , -0.29918468],
       [-1.82785476, -1.18365158,  1.26481967, -0.71811599],
       [-0.77575297, -1.35853789, -1.29492926,  0.68741658],
       [-2.08032727, -1.36079547, -0.25561963, -0.56360436]])

In [37]:
arr = np.arange(28)

In [41]:
arr.reshape(7,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr = np.random.randint(0,50,10) #from 0 to 50 get 10 random elements

In [43]:
ranarr

array([10, 13, 36,  5, 30, 44,  4,  1, 18, 24])

In [44]:
ranarr.argmax()

5

In [46]:
ranarr.max() # max is 44 at index 5

44

# Indexing and Slicing

In [50]:
arr = np.arange(1,12)

In [51]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
arr[8]

9

In [53]:
arr[1:5]

array([2, 3, 4, 5])

In [54]:
arr[:5]

array([1, 2, 3, 4, 5])

In [55]:
arr[:-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
arr[0:5] = 100

In [58]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10,  11])

In [59]:
arr_2d = np.array([[10,15,20],[25,30,35],[40,45,50]])

In [60]:
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [62]:
arr_2d[0][1]

15

In [63]:
arr_2d[1,2]

35

In [66]:
arr_2d[:2, 1:]

array([[15, 20],
       [30, 35]])

In [67]:
arr = np.arange(0,11)

In [68]:
bool_arr = arr > 5

In [69]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True], dtype=bool)

In [70]:
arr[arr < 3]

array([0, 1, 2])

In [71]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [72]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])