___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### Create an array of 10 ones

In [4]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Create an array of 10 fives

In [5]:
np.ones(10) * 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### Create an array of the integers from 10 to 50

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
arr = np.arange(0,9)
arr.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [14]:
np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Use NumPy to generate a random number between 0 and 1

In [20]:
np.random.rand(1)

array([ 0.26228678])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [22]:
np.random.randn(25)

array([ 0.71781566, -1.17275542, -0.13514953, -0.11974201,  0.07746356,
        0.35226391, -0.06461575,  1.22983429,  0.20667148,  0.95970861,
       -0.1889259 , -0.83455098,  0.64260714,  0.29585376,  0.72798155,
       -0.82418764, -1.62033177,  0.39604999, -1.9135353 , -0.40308035,
        0.61417756, -0.68438361, -0.42223074,  0.1401217 , -1.47150868])

#### Create the following matrix:

In [25]:
np.random.rand(10,10)

array([[ 0.54240604,  0.84156829,  0.28735168,  0.54642257,  0.09091536,
         0.74658419,  0.14403036,  0.7080051 ,  0.21597447,  0.30812136],
       [ 0.19278594,  0.5462772 ,  0.46152973,  0.26244271,  0.29119388,
         0.04336158,  0.26894866,  0.03646913,  0.26435731,  0.37417014],
       [ 0.81414815,  0.47225082,  0.45750271,  0.65353552,  0.17846548,
         0.75515319,  0.62705237,  0.97710351,  0.48970498,  0.84219368],
       [ 0.95576903,  0.19747493,  0.90790966,  0.67258561,  0.21945246,
         0.27076154,  0.52623846,  0.71682846,  0.5616891 ,  0.62337254],
       [ 0.8143853 ,  0.93317938,  0.42970357,  0.60959939,  0.79520839,
         0.2337592 ,  0.65183556,  0.74316242,  0.68227606,  0.64854885],
       [ 0.21652288,  0.56408105,  0.23528242,  0.67574834,  0.60691015,
         0.51648313,  0.14085831,  0.26989273,  0.52390683,  0.71538819],
       [ 0.1583119 ,  0.45532063,  0.50421164,  0.26963402,  0.24554822,
         0.56648419,  0.24998079,  0.19306902

#### Create an array of 20 linearly spaced points between 0 and 1:

In [26]:
np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [27]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [33]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [34]:
mat[3,4]

20

In [42]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [43]:
mat[4]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [45]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [46]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [47]:
mat.std()

7.2111025509279782

#### Get the sum of all the columns in mat

In [48]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!